import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Importa a fonte Inter do Google Fonts
import "./globals.css";

// Define a fonte Inter
const inter = Inter({
  subsets: ["latin"], // Subconjunto necessário para a maioria dos projetos
  variable: "--font-inter", // Nome da variável CSS para aplicar a fonte
});

export const metadata: Metadata = {
  title: "Bug find by undf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
