import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Importa a fonte Inter do Google Fonts
import "./globals.css";
import { cn } from "@/lib/utils";

// Define a fonte Inter
const inter = Inter({
  subsets: ["latin"], // Subconjunto necessário para a maioria dos projetos
  variable: "--font-inter", // Nome da variável CSS para aplicar a fonte
});

export const metadata: Metadata = {
  title: "Bug find by undf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable)}>
        {children}
      </body>
    </html>
  )
}
